# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'weather.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPlainTextEdit, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_WeatherChercker(object):
    def setupUi(self, WeatherChercker):
        if not WeatherChercker.objectName():
            WeatherChercker.setObjectName(u"WeatherChercker")
        WeatherChercker.resize(1189, 825)
        WeatherChercker.setAutoFillBackground(False)
        WeatherChercker.setStyleSheet(u"background-color: #0315cc   ;")
        self.centralwidget = QWidget(WeatherChercker)
        self.centralwidget.setObjectName(u"centralwidget")
        self.WeatherChecker = QLabel(self.centralwidget)
        self.WeatherChecker.setObjectName(u"WeatherChecker")
        self.WeatherChecker.setGeometry(QRect(20, 20, 721, 461))
        self.WeatherChecker.setStyleSheet(u"")
        self.WeatherChecker.setPixmap(QPixmap(u"ui/weather_map.jpg"))
        self.WeatherChecker.setScaledContents(True)
        self.temperature_box = QLabel(self.centralwidget)
        self.temperature_box.setObjectName(u"temperature_box")
        self.temperature_box.setGeometry(QRect(130, 530, 41, 31))
        self.temperature_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.winspeedtext = QLabel(self.centralwidget)
        self.winspeedtext.setObjectName(u"winspeedtext")
        self.winspeedtext.setGeometry(QRect(240, 650, 91, 31))
        self.winspeedtext.setStyleSheet(u"background-color: #ffffff   ;")
        self.timezonetext = QLabel(self.centralwidget)
        self.timezonetext.setObjectName(u"timezonetext")
        self.timezonetext.setGeometry(QRect(40, 590, 81, 31))
        self.timezonetext.setStyleSheet(u"background-color: #ffffff   ;")
        self.humiditytext = QLabel(self.centralwidget)
        self.humiditytext.setObjectName(u"humiditytext")
        self.humiditytext.setGeometry(QRect(240, 590, 81, 31))
        self.humiditytext.setStyleSheet(u"background-color: #ffffff   ;")
        self.sunrisetext = QLabel(self.centralwidget)
        self.sunrisetext.setObjectName(u"sunrisetext")
        self.sunrisetext.setGeometry(QRect(470, 550, 111, 31))
        self.sunrisetext.setStyleSheet(u"background-color: #ffffff   ;")
        self.feelsliketext = QLabel(self.centralwidget)
        self.feelsliketext.setObjectName(u"feelsliketext")
        self.feelsliketext.setGeometry(QRect(240, 530, 81, 31))
        self.feelsliketext.setStyleSheet(u"background-color: #ffffff   ;")
        self.sunsettext = QLabel(self.centralwidget)
        self.sunsettext.setObjectName(u"sunsettext")
        self.sunsettext.setGeometry(QRect(470, 620, 101, 31))
        self.sunsettext.setStyleSheet(u"background-color: #ffffff   ;")
        self.skyclearncetext = QLabel(self.centralwidget)
        self.skyclearncetext.setObjectName(u"skyclearncetext")
        self.skyclearncetext.setGeometry(QRect(750, 580, 111, 31))
        self.skyclearncetext.setStyleSheet(u"background-color: #ffffff   ;")
        self.pressuretext = QLabel(self.centralwidget)
        self.pressuretext.setObjectName(u"pressuretext")
        self.pressuretext.setGeometry(QRect(40, 650, 101, 31))
        self.pressuretext.setStyleSheet(u"background-color: #ffffff   ;")
        self.temperature_text = QLabel(self.centralwidget)
        self.temperature_text.setObjectName(u"temperature_text")
        self.temperature_text.setGeometry(QRect(40, 530, 91, 31))
        self.temperature_text.setStyleSheet(u"background-color: #ffffff   ;")
        self.timezone_box = QLabel(self.centralwidget)
        self.timezone_box.setObjectName(u"timezone_box")
        self.timezone_box.setGeometry(QRect(120, 590, 71, 31))
        self.timezone_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.pressure_box = QLabel(self.centralwidget)
        self.pressure_box.setObjectName(u"pressure_box")
        self.pressure_box.setGeometry(QRect(140, 650, 51, 31))
        self.pressure_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.humidity_box = QLabel(self.centralwidget)
        self.humidity_box.setObjectName(u"humidity_box")
        self.humidity_box.setGeometry(QRect(320, 590, 51, 31))
        self.humidity_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.windspeed_box = QLabel(self.centralwidget)
        self.windspeed_box.setObjectName(u"windspeed_box")
        self.windspeed_box.setGeometry(QRect(330, 650, 41, 31))
        self.windspeed_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.feelslike_box = QLabel(self.centralwidget)
        self.feelslike_box.setObjectName(u"feelslike_box")
        self.feelslike_box.setGeometry(QRect(320, 530, 51, 31))
        self.feelslike_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.sunrisetime_box = QLabel(self.centralwidget)
        self.sunrisetime_box.setObjectName(u"sunrisetime_box")
        self.sunrisetime_box.setGeometry(QRect(580, 550, 71, 31))
        self.sunrisetime_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.sunsettime_box = QLabel(self.centralwidget)
        self.sunsettime_box.setObjectName(u"sunsettime_box")
        self.sunsettime_box.setGeometry(QRect(570, 620, 81, 31))
        self.sunsettime_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.skyclearance_box = QLabel(self.centralwidget)
        self.skyclearance_box.setObjectName(u"skyclearance_box")
        self.skyclearance_box.setGeometry(QRect(860, 580, 71, 31))
        self.skyclearance_box.setStyleSheet(u"background-color: #ffffff   ;")
        self.input_field = QLineEdit(self.centralwidget)
        self.input_field.setObjectName(u"input_field")
        self.input_field.setGeometry(QRect(820, 170, 171, 28))
        self.input_field.setStyleSheet(u"background-color: #ffffff   ;\n"
"font: 600 italic 11pt \"Noto Sans\";")
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(820, 80, 281, 81))
        self.plainTextEdit.setStyleSheet(u"background-color: #ffffff   ;")
        self.submit_button = QPushButton(self.centralwidget)
        self.submit_button.setObjectName(u"submit_button")
        self.submit_button.setGeometry(QRect(1000, 170, 101, 29))
        self.submit_button.setStyleSheet(u"background-color: #ffffff   ;")
        WeatherChercker.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(WeatherChercker)
        self.statusbar.setObjectName(u"statusbar")
        WeatherChercker.setStatusBar(self.statusbar)

        self.retranslateUi(WeatherChercker)

        QMetaObject.connectSlotsByName(WeatherChercker)
    # setupUi

    def retranslateUi(self, WeatherChercker):
        WeatherChercker.setWindowTitle(QCoreApplication.translate("WeatherChercker", u"Weather Checker", None))
        self.WeatherChecker.setText("")
        self.temperature_box.setText("")
        self.winspeedtext.setText(QCoreApplication.translate("WeatherChercker", u"Wind Speed:", None))
        self.timezonetext.setText(QCoreApplication.translate("WeatherChercker", u"Timezone:", None))
        self.humiditytext.setText(QCoreApplication.translate("WeatherChercker", u"Humidity:", None))
        self.sunrisetext.setText(QCoreApplication.translate("WeatherChercker", u"Sunrise Time:", None))
        self.feelsliketext.setText(QCoreApplication.translate("WeatherChercker", u"Feels Like:", None))
        self.sunsettext.setText(QCoreApplication.translate("WeatherChercker", u"Sunset Time:", None))
        self.skyclearncetext.setText(QCoreApplication.translate("WeatherChercker", u"Sky Clearnce:", None))
        self.pressuretext.setText(QCoreApplication.translate("WeatherChercker", u"Pressure(hPa):", None))
        self.temperature_text.setText(QCoreApplication.translate("WeatherChercker", u"Temprature:", None))
        self.timezone_box.setText("")
        self.pressure_box.setText("")
        self.humidity_box.setText("")
        self.windspeed_box.setText("")
        self.feelslike_box.setText("")
        self.sunrisetime_box.setText("")
        self.sunsettime_box.setText("")
        self.skyclearance_box.setText("")
        self.plainTextEdit.setPlainText(QCoreApplication.translate("WeatherChercker", u"All of the data is shown in european metric system. The field below lets you look up any location you want", None))
        self.submit_button.setText(QCoreApplication.translate("WeatherChercker", u"PushButton", None))
    # retranslateUi

